security:
    firewalls:
        main:
            pattern: ^/
            anonymous: true
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            logout:
                path: app_logout
                target: homepage
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
                name: REMEMBER_ME


    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }